### ISSUE TITLE
[BUG] Rendering is broken for Cosmic Reach 0.1.44

### ISSUE THREAD

**Issue by StartsMercury** [Shfloop/SimplyShaders#2]
The shaders used below is the same as described in the workaround section of #1 and paired with the Dynamic Sky lighting.

![2024-08-11_09-02-53](https://github.com/user-attachments/assets/68524f3d-7382-4c40-b53a-f011befab8ef)

**Comment by Shfloop** [comment]
Should be good now with 1.0.3
